### ISSUE TITLE
problem when using it

### ISSUE THREAD

**Issue by Gasferr** [Nexilist/xap-client#2]
When the gui appears, my keyboard freezes, why is this? By the way I have updated the offers and it is still doing the same

**Comment by Moepu** [comment]
Because GLFW works differently from Windows, you'll have to press Insert to disable the menu before interacting with your screen.

**Comment by Gasferr** [comment]
It doesn't let me press any key on the keyboard when I run the command sudo ./xapclient , The keyboard stops working completely, the mouse continues to work but the keyboard no longer works either in the game or outside the game

**Comment by Moepu** [comment]
I'll take a look at it when I'm home, I never had any issues with it but I'll try to redo the Menu's input system.

**Comment by Gasferr** [comment]
good man is appreciated very much

**Comment by Gasferr** [comment]
Does it have anything to do with the Linux distribution? Isn't it a coding problem?
